name: Deploy

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v6
        with:
          version: latest

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          package-manager-cache: false

      - run: pnpm install --frozen-lockfile

      - run: pnpm build

      - run: pnpm test

      - run: npx semantic-release
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
